#!/usr/bin/env python3
"""Generate data/countries.json with niche vs mainstream cuisine tiers."""

from __future__ import annotations

import json
from pathlib import Path

NICHE = {
    "GE", "AM", "AZ", "AL", "BA", "RS", "ME", "MK", "RO", "BG", "MD", "SI", "HR",
    "IR", "IQ", "SY", "JO", "OM", "YE", "KZ", "UZ", "KG", "TJ", "TM",
    "SN", "GH", "NG", "CM", "CI", "UG", "TZ", "RW", "SO", "ER", "SD", "MG", "MU",
    "HT", "TT", "GY", "SR", "BO", "PY", "EC", "CO", "NI", "HN",
    "BT", "NP", "LK", "MM", "LA", "KH", "MN", "TL",
}

# code, nameZh, nameEn, region
COUNTRIES = [
    ("AF", "阿富汗", "Afghanistan", "亚洲"),
    ("AL", "阿尔巴尼亚", "Albania", "欧洲"),
    ("DZ", "阿尔及利亚", "Algeria", "非洲"),
    ("AD", "安道尔", "Andorra", "欧洲"),
    ("AO", "安哥拉", "Angola", "非洲"),
    ("AG", "安提瓜和巴布达", "Antigua and Barbuda", "加勒比 / 拉美"),
    ("AR", "阿根廷", "Argentina", "加勒比 / 拉美"),
    ("AM", "亚美尼亚", "Armenia", "欧洲"),
    ("AU", "澳大利亚", "Australia", "大洋洲"),
    ("AT", "奥地利", "Austria", "欧洲"),
    ("AZ", "阿塞拜疆", "Azerbaijan", "欧洲"),
    ("BS", "巴哈马", "Bahamas", "加勒比 / 拉美"),
    ("BH", "巴林", "Bahrain", "亚洲"),
    ("BD", "孟加拉国", "Bangladesh", "亚洲"),
    ("BB", "巴巴多斯", "Barbados", "加勒比 / 拉美"),
    ("BY", "白俄罗斯", "Belarus", "欧洲"),
    ("BE", "比利时", "Belgium", "欧洲"),
    ("BZ", "伯利兹", "Belize", "加勒比 / 拉美"),
    ("BJ", "贝宁", "Benin", "非洲"),
    ("BT", "不丹", "Bhutan", "亚洲"),
    ("BO", "玻利维亚", "Bolivia", "加勒比 / 拉美"),
    ("BA", "波斯尼亚", "Bosnia and Herzegovina", "欧洲"),
    ("BW", "博茨瓦纳", "Botswana", "非洲"),
    ("BR", "巴西", "Brazil", "加勒比 / 拉美"),
    ("BN", "文莱", "Brunei", "亚洲"),
    ("BG", "保加利亚", "Bulgaria", "欧洲"),
    ("BF", "布基纳法索", "Burkina Faso", "非洲"),
    ("BI", "布隆迪", "Burundi", "非洲"),
    ("CV", "佛得角", "Cabo Verde", "非洲"),
    ("KH", "柬埔寨", "Cambodia", "亚洲"),
    ("CM", "喀麦隆", "Cameroon", "非洲"),
    ("CA", "加拿大", "Canada", "北美"),
    ("CF", "中非", "Central African Republic", "非洲"),
    ("TD", "乍得", "Chad", "非洲"),
    ("CL", "智利", "Chile", "加勒比 / 拉美"),
    ("CN", "中国", "China", "亚洲"),
    ("CO", "哥伦比亚", "Colombia", "加勒比 / 拉美"),
    ("KM", "科摩罗", "Comoros", "非洲"),
    ("CG", "刚果（布）", "Congo", "非洲"),
    ("CD", "刚果（金）", "Democratic Republic of the Congo", "非洲"),
    ("CR", "哥斯达黎加", "Costa Rica", "加勒比 / 拉美"),
    ("CI", "科特迪瓦", "Côte d'Ivoire", "非洲"),
    ("HR", "克罗地亚", "Croatia", "欧洲"),
    ("CU", "古巴", "Cuba", "加勒比 / 拉美"),
    ("CY", "塞浦路斯", "Cyprus", "欧洲"),
    ("CZ", "捷克", "Czechia", "欧洲"),
    ("DK", "丹麦", "Denmark", "欧洲"),
    ("DJ", "吉布提", "Djibouti", "非洲"),
    ("DM", "多米尼克", "Dominica", "加勒比 / 拉美"),
    ("DO", "多米尼加", "Dominican Republic", "加勒比 / 拉美"),
    ("EC", "厄瓜多尔", "Ecuador", "加勒比 / 拉美"),
    ("EG", "埃及", "Egypt", "非洲"),
    ("SV", "萨尔瓦多", "El Salvador", "加勒比 / 拉美"),
    ("GQ", "赤道几内亚", "Equatorial Guinea", "非洲"),
    ("ER", "厄立特里亚", "Eritrea", "非洲"),
    ("EE", "爱沙尼亚", "Estonia", "欧洲"),
    ("SZ", "斯威士兰", "Eswatini", "非洲"),
    ("ET", "埃塞俄比亚", "Ethiopia", "非洲"),
    ("FJ", "斐济", "Fiji", "大洋洲"),
    ("FI", "芬兰", "Finland", "欧洲"),
    ("FR", "法国", "France", "欧洲"),
    ("GA", "加蓬", "Gabon", "非洲"),
    ("GM", "冈比亚", "Gambia", "非洲"),
    ("GE", "格鲁吉亚", "Georgia", "欧洲"),
    ("DE", "德国", "Germany", "欧洲"),
    ("GH", "加纳", "Ghana", "非洲"),
    ("GR", "希腊", "Greece", "欧洲"),
    ("GD", "格林纳达", "Grenada", "加勒比 / 拉美"),
    ("GT", "危地马拉", "Guatemala", "加勒比 / 拉美"),
    ("GN", "几内亚", "Guinea", "非洲"),
    ("GW", "几内亚比绍", "Guinea-Bissau", "非洲"),
    ("GY", "圭亚那", "Guyana", "加勒比 / 拉美"),
    ("HT", "海地", "Haiti", "加勒比 / 拉美"),
    ("HN", "洪都拉斯", "Honduras", "加勒比 / 拉美"),
    ("HU", "匈牙利", "Hungary", "欧洲"),
    ("IS", "冰岛", "Iceland", "欧洲"),
    ("IN", "印度", "India", "亚洲"),
    ("ID", "印度尼西亚", "Indonesia", "亚洲"),
    ("IR", "伊朗", "Iran", "亚洲"),
    ("IQ", "伊拉克", "Iraq", "亚洲"),
    ("IE", "爱尔兰", "Ireland", "欧洲"),
    ("IL", "以色列", "Israel", "亚洲"),
    ("IT", "意大利", "Italy", "欧洲"),
    ("JM", "牙买加", "Jamaica", "加勒比 / 拉美"),
    ("JP", "日本", "Japan", "亚洲"),
    ("JO", "约旦", "Jordan", "亚洲"),
    ("KZ", "哈萨克斯坦", "Kazakhstan", "亚洲"),
    ("KE", "肯尼亚", "Kenya", "非洲"),
    ("KI", "基里巴斯", "Kiribati", "大洋洲"),
    ("KP", "朝鲜", "North Korea", "亚洲"),
    ("KR", "韩国", "South Korea", "亚洲"),
    ("KW", "科威特", "Kuwait", "亚洲"),
    ("KG", "吉尔吉斯斯坦", "Kyrgyzstan", "亚洲"),
    ("LA", "老挝", "Laos", "亚洲"),
    ("LV", "拉脱维亚", "Latvia", "欧洲"),
    ("LB", "黎巴嫩", "Lebanon", "亚洲"),
    ("LS", "莱索托", "Lesotho", "非洲"),
    ("LR", "利比里亚", "Liberia", "非洲"),
    ("LY", "利比亚", "Libya", "非洲"),
    ("LI", "列支敦士登", "Liechtenstein", "欧洲"),
    ("LT", "立陶宛", "Lithuania", "欧洲"),
    ("LU", "卢森堡", "Luxembourg", "欧洲"),
    ("MG", "马达加斯加", "Madagascar", "非洲"),
    ("MW", "马拉维", "Malawi", "非洲"),
    ("MY", "马来西亚", "Malaysia", "亚洲"),
    ("MV", "马尔代夫", "Maldives", "亚洲"),
    ("ML", "马里", "Mali", "非洲"),
    ("MT", "马耳他", "Malta", "欧洲"),
    ("MH", "马绍尔群岛", "Marshall Islands", "大洋洲"),
    ("MR", "毛里塔尼亚", "Mauritania", "非洲"),
    ("MU", "毛里求斯", "Mauritius", "非洲"),
    ("MX", "墨西哥", "Mexico", "加勒比 / 拉美"),
    ("FM", "密克罗尼西亚", "Micronesia", "大洋洲"),
    ("MD", "摩尔多瓦", "Moldova", "欧洲"),
    ("MC", "摩纳哥", "Monaco", "欧洲"),
    ("MN", "蒙古", "Mongolia", "亚洲"),
    ("ME", "黑山", "Montenegro", "欧洲"),
    ("MA", "摩洛哥", "Morocco", "非洲"),
    ("MZ", "莫桑比克", "Mozambique", "非洲"),
    ("MM", "缅甸", "Myanmar", "亚洲"),
    ("NA", "纳米比亚", "Namibia", "非洲"),
    ("NR", "瑙鲁", "Nauru", "大洋洲"),
    ("NP", "尼泊尔", "Nepal", "亚洲"),
    ("NL", "荷兰", "Netherlands", "欧洲"),
    ("NZ", "新西兰", "New Zealand", "大洋洲"),
    ("NI", "尼加拉瓜", "Nicaragua", "加勒比 / 拉美"),
    ("NE", "尼日尔", "Niger", "非洲"),
    ("NG", "尼日利亚", "Nigeria", "非洲"),
    ("MK", "北马其顿", "North Macedonia", "欧洲"),
    ("NO", "挪威", "Norway", "欧洲"),
    ("OM", "阿曼", "Oman", "亚洲"),
    ("PK", "巴基斯坦", "Pakistan", "亚洲"),
    ("PW", "帕劳", "Palau", "大洋洲"),
    ("PS", "巴勒斯坦", "Palestine", "亚洲"),
    ("PA", "巴拿马", "Panama", "加勒比 / 拉美"),
    ("PG", "巴布亚新几内亚", "Papua New Guinea", "大洋洲"),
    ("PY", "巴拉圭", "Paraguay", "加勒比 / 拉美"),
    ("PE", "秘鲁", "Peru", "加勒比 / 拉美"),
    ("PH", "菲律宾", "Philippines", "亚洲"),
    ("PL", "波兰", "Poland", "欧洲"),
    ("PT", "葡萄牙", "Portugal", "欧洲"),
    ("QA", "卡塔尔", "Qatar", "亚洲"),
    ("RO", "罗马尼亚", "Romania", "欧洲"),
    ("RU", "俄罗斯", "Russia", "欧洲"),
    ("RW", "卢旺达", "Rwanda", "非洲"),
    ("KN", "圣基茨和尼维斯", "Saint Kitts and Nevis", "加勒比 / 拉美"),
    ("LC", "圣卢西亚", "Saint Lucia", "加勒比 / 拉美"),
    ("VC", "圣文森特和格林纳丁斯", "Saint Vincent and the Grenadines", "加勒比 / 拉美"),
    ("WS", "萨摩亚", "Samoa", "大洋洲"),
    ("SM", "圣马力诺", "San Marino", "欧洲"),
    ("ST", "圣多美和普林西比", "Sao Tome and Principe", "非洲"),
    ("SA", "沙特阿拉伯", "Saudi Arabia", "亚洲"),
    ("SN", "塞内加尔", "Senegal", "非洲"),
    ("RS", "塞尔维亚", "Serbia", "欧洲"),
    ("SC", "塞舌尔", "Seychelles", "非洲"),
    ("SL", "塞拉利昂", "Sierra Leone", "非洲"),
    ("SG", "新加坡", "Singapore", "亚洲"),
    ("SK", "斯洛伐克", "Slovakia", "欧洲"),
    ("SI", "斯洛文尼亚", "Slovenia", "欧洲"),
    ("SB", "所罗门群岛", "Solomon Islands", "大洋洲"),
    ("SO", "索马里", "Somalia", "非洲"),
    ("ZA", "南非", "South Africa", "非洲"),
    ("SS", "南苏丹", "South Sudan", "非洲"),
    ("ES", "西班牙", "Spain", "欧洲"),
    ("LK", "斯里兰卡", "Sri Lanka", "亚洲"),
    ("SD", "苏丹", "Sudan", "非洲"),
    ("SR", "苏里南", "Suriname", "加勒比 / 拉美"),
    ("SE", "瑞典", "Sweden", "欧洲"),
    ("CH", "瑞士", "Switzerland", "欧洲"),
    ("SY", "叙利亚", "Syria", "亚洲"),
    ("TW", "台湾", "Taiwan", "亚洲"),
    ("TJ", "塔吉克斯坦", "Tajikistan", "亚洲"),
    ("TZ", "坦桑尼亚", "Tanzania", "非洲"),
    ("TH", "泰国", "Thailand", "亚洲"),
    ("TL", "东帝汶", "Timor-Leste", "亚洲"),
    ("TG", "多哥", "Togo", "非洲"),
    ("TO", "汤加", "Tonga", "大洋洲"),
    ("TT", "特立尼达和多巴哥", "Trinidad and Tobago", "加勒比 / 拉美"),
    ("TN", "突尼斯", "Tunisia", "非洲"),
    ("TR", "土耳其", "Turkey", "亚洲"),
    ("TM", "土库曼斯坦", "Turkmenistan", "亚洲"),
    ("TV", "图瓦卢", "Tuvalu", "大洋洲"),
    ("UG", "乌干达", "Uganda", "非洲"),
    ("UA", "乌克兰", "Ukraine", "欧洲"),
    ("AE", "阿联酋", "United Arab Emirates", "亚洲"),
    ("GB", "英国", "United Kingdom", "欧洲"),
    ("US", "美国", "United States", "北美"),
    ("UY", "乌拉圭", "Uruguay", "加勒比 / 拉美"),
    ("UZ", "乌兹别克斯坦", "Uzbekistan", "亚洲"),
    ("VU", "瓦努阿图", "Vanuatu", "大洋洲"),
    ("VA", "梵蒂冈", "Vatican City", "欧洲"),
    ("VE", "委内瑞拉", "Venezuela", "加勒比 / 拉美"),
    ("VN", "越南", "Vietnam", "亚洲"),
    ("YE", "也门", "Yemen", "亚洲"),
    ("ZM", "赞比亚", "Zambia", "非洲"),
    ("ZW", "津巴布韦", "Zimbabwe", "非洲"),
    ("XK", "科索沃", "Kosovo", "欧洲"),
    ("HK", "香港", "Hong Kong", "亚洲"),
    ("MO", "澳门", "Macao", "亚洲"),
]


def flag(code: str) -> str:
    return "".join(chr(0x1F1E6 + ord(ch) - 65) for ch in code)


def main() -> None:
    missing = NICHE - {row[0] for row in COUNTRIES}
    if missing:
        raise SystemExit(f"niche countries missing from catalog: {sorted(missing)}")

    records = []
    for code, name_zh, name_en, region in COUNTRIES:
        records.append(
            {
                "code": code,
                "nameZh": name_zh,
                "nameEn": name_en,
                "flag": flag(code),
                "region": region,
                "cuisineTier": "niche" if code in NICHE else "mainstream",
            }
        )

    out = Path("data/countries.json")
    out.write_text(json.dumps(records, ensure_ascii=False, indent=2) + "\n")
    niche_count = sum(1 for row in records if row["cuisineTier"] == "niche")
    print(f"wrote {out} ({len(records)} countries, {niche_count} niche)")


if __name__ == "__main__":
    main()
